# Generated by Django 5.1 on 2024-08-30 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_remove_tasks_description_remove_tasks_scheduled_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='end_time',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='tasks',
            old_name='start_time',
            new_name='start',
        ),
    ]
