# Generated by Django 5.1 on 2024-08-30 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='yadhu', max_length=200),
            preserve_default=False,
        ),
    ]
